#config for database
spring.data.mongodb.username=tyzer
spring.data.mongodb.password=tyzer
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=chat_app
spring.data.mongodb.authentication-database=admin
#port for server
server.port=8088